//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManagementApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public int Id { get; set; }
        public int ContractId { get; set; }
        public int DivisionId { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
